apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrafusion-config-service
  namespace: terrafusion-system
  labels:
    app: terrafusion-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terrafusion-config-service
  template:
    metadata:
      labels:
        app: terrafusion-config-service
    spec:
      containers:
        - name: config-service
          image: terrafusion/config-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: terrafusion-update-service
  namespace: terrafusion-system
spec:
  selector:
    app: terrafusion-config-service
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP