version: '3.8'

services:
  gama-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - gama-backend

  gama-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - WASM_PATH=/app/wasm
    volumes:
      - ./data:/app/data
      - ./wasm:/app/wasm

  gama-agents:
    build:
      context: .
      dockerfile: Dockerfile.agents
    environment:
      - AGENT_CONFIG_PATH=/app/config
      - MODEL_PATH=/app/models
    volumes:
      - ./agents:/app/agents
      - ./config:/app/config
      - ./models:/app/models

  gama-spatial:
    build:
      context: .
      dockerfile: Dockerfile.spatial
    ports:
      - "8080:8080"
    environment:
      - GEOSERVER_URL=${GEOSERVER_URL}
      - POSTGIS_URL=${POSTGIS_URL}
    volumes:
      - ./spatial:/app/spatial

networks:
  gama-network:
    driver: bridge

volumes:
  gama-data:
    driver: local
  gama-models:
    driver: local
  gama-cache:
    driver: local 