global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gama-frontend'
    static_configs:
      - targets: ['gama-frontend:3000']

  - job_name: 'gama-backend'
    static_configs:
      - targets: ['gama-backend:8000']

  - job_name: 'gama-agents'
    static_configs:
      - targets: ['gama-agents:8000']

  - job_name: 'gama-spatial'
    static_configs:
      - targets: ['gama-spatial:8080'] 