apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: driftguards.terrafusion.ai
  labels:
    app: driftguard-operator
    component: crd
spec:
  group: terrafusion.ai
  names:
    kind: DriftGuard
    plural: driftguards
    singular: driftguard
    shortNames:
      - dg
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - targetKind
                - targetName
                - expectedHash
              properties:
                targetKind:
                  type: string
                  description: "Kind of resource to monitor (ConfigMap, Secret, GAMAConfig, etc.)"
                targetName:
                  type: string
                  description: "Name of the resource to monitor"
                targetNamespace:
                  type: string
                  description: "Namespace of the resource (defaults to DriftGuard's namespace if not specified)"
                expectedHash:
                  type: string
                  pattern: "^[a-fA-F0-9]{64}$"
                  description: "Expected SHA-256 hash of the configuration"
                autoRemediate:
                  type: boolean
                  default: false
                  description: "Automatically remediate drift when detected"
                maxFailuresBeforeAlert:
                  type: integer
                  default: 3
                  minimum: 1
                  description: "Number of consecutive failures before triggering an alert"
                sourceOfTruthRef:
                  type: object
                  properties:
                    kind:
                      type: string
                      enum: ["git", "configmap", "secret", "service"]
                      description: "Type of source of truth"
                    name:
                      type: string
                      description: "Name of the source of truth"
                    namespace:
                      type: string
                      description: "Namespace of the source of truth"
                    path:
                      type: string
                      description: "Path within the source of truth"
                  required:
                    - kind
                    - name
            status:
              type: object
              properties:
                lastChecked:
                  type: string
                  description: "Timestamp of last check"
                hashMatch:
                  type: boolean
                  nullable: true
                  description: "Whether the current hash matches expected hash"
                currentHash:
                  type: string
                  description: "Current hash of the resource"
                consecutiveFailures:
                  type: integer
                  default: 0
                  description: "Count of consecutive drift detections"
                remediated:
                  type: boolean
                  nullable: true
                  description: "Whether remediation was applied"
                alerted:
                  type: boolean
                  default: false
                  description: "Whether an alert was raised"
                status:
                  type: string
                  enum: ["Healthy", "Drifted", "Error", "Invalid"]
                  description: "Status of the DriftGuard resource"
                reason:
                  type: string
                  description: "Reason for any error status"
      additionalPrinterColumns:
        - name: Target
          type: string
          jsonPath: .spec.targetKind
        - name: Name
          type: string
          jsonPath: .spec.targetName
        - name: Status
          type: string
          jsonPath: .status.status
        - name: Matched
          type: boolean
          jsonPath: .status.hashMatch
        - name: Auto-Remediate
          type: boolean
          jsonPath: .spec.autoRemediate
        - name: Last Checked
          type: string
          jsonPath: .status.lastChecked
          format: date-time
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}