apiVersion: terrafusion.ai/v1
kind: DriftGuard
metadata:
  name: db-credentials-guard
  namespace: terrafusion-system
  labels:
    app: terrafusion-database
    component: credentials
spec:
  # Monitor a Secret resource
  targetKind: Secret
  targetName: db-credentials
  targetNamespace: terrafusion-system
  
  # Expected SHA-256 hash of the Secret data
  expectedHash: "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b"
  
  # For sensitive resources like Secrets, we want immediate alerts
  autoRemediate: true
  maxFailuresBeforeAlert: 1
  
  # Configuration source of truth reference - using a reference Secret
  sourceOfTruthRef:
    kind: secret
    name: db-credentials-reference
    namespace: terrafusion-security
    # No path needed for Secret references